SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS `gmod_top` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CID` varchar(20) NOT NULL,
  `count` int(20) NOT NULL DEFAULT '1',
  `last` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0 ;
